name: health_messenger_ui_example
description: Example app for health_messenger_ui.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  health_messenger_ui:
    path: ..
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
